import Link from 'next/link'
import { branchContent } from '@/lib/academy-content'

export const metadata = { title: 'Tác động cột sống | Mộc Việt', description: 'Lộ trình học Tác động cột sống tại Mộc Việt.' }

export default function SpinePage() {
  const content = branchContent.cot_song
  return <BranchPage title={content.title} intro={content.intro} principles={content.principles} packages={content.packages} />
}

function BranchPage({ title, intro, principles, packages }: { title: string; intro: string; principles: string[]; packages: typeof branchContent.cot_song.packages }) {
  return <main className="page-shell"><header className="page-header"><div className="container"><nav className="site-nav"><Link className="brand" href="/">Mộc Việt<span>.</span></Link><div className="nav-links"><Link href="/yoga">Yoga</Link><Link href="/lich-khai-giang">Lịch khai giảng</Link><Link href="/kien-thuc">Kiến thức</Link></div><Link className="button button-small button-dark" href="/dang-ky-tu-van">Nhận tư vấn</Link></nav></div></header><section className="page-hero"><div className="container"><p className="eyebrow">LỘ TRÌNH ĐÀO TẠO · TĐCS</p><h1>{title}</h1><p>{intro}</p></div></section><section className="section container"><div className="section-heading"><p className="eyebrow">KHUNG HỌC TẬP</p><h2>Học theo hệ thống, không học theo lời hứa.</h2></div><div className="branch-grid">{principles.map((item, index) => <article className="branch-note" key={item}><span className="package-code">0{index + 1}</span><p>{item}</p></article>)}</div></section><section className="section section-tint"><div className="container"><div className="section-heading"><p className="eyebrow">A1 · A2 · A3</p><h2>Các nấc học được công bố theo phạm vi.</h2></div><div className="package-grid">{packages.map((item) => <Link className="package-card" href={`/khoa-hoc/${item.slug}`} key={item.code}><div className="package-top"><span className="package-code">{item.code}</span><span>{item.requiresScreening ? 'Có xét phù hợp' : 'Tự chọn chương trình'}</span></div><h3>{item.name}</h3><p>{item.summary}</p><div className="package-meta"><span>{item.accessMonths} tháng nội dung</span><span>{item.includesCertification ? 'Có quyền dự đánh giá' : 'Không bao gồm chứng nhận'}</span></div></Link>)}</div></div></section><section className="section container callout-section"><div><p className="eyebrow">PHẠM VI ĐÀO TẠO</p><h2>Chương trình không thay thế thăm khám, chẩn đoán hoặc điều trị.</h2><p>Thực hành chỉ diễn ra trong phạm vi nội dung, điều kiện và sự giám sát được công bố. Hãy gửi câu hỏi nếu bạn cần biết chương trình nào phù hợp.</p></div><Link className="button button-dark" href="/dang-ky-tu-van">Đăng ký tư vấn</Link></section><footer className="site-footer"><div className="container footer-bottom"><span>© 2026 Mộc Việt</span><span>Chứng nhận của Mộc Việt không mặc nhiên là giấy phép hành nghề.</span></div></footer></main>
}
