import Link from 'next/link'
import { branchContent } from '@/lib/academy-content'

export const metadata = { title: 'Yoga | Mộc Việt', description: 'Các chương trình Yoga của Mộc Việt theo mục tiêu và mức độ hỗ trợ.' }

export default function YogaPage() {
  const content = branchContent.yoga
  return <main className="page-shell"><header className="page-header"><div className="container"><nav className="site-nav"><Link className="brand" href="/">Mộc Việt<span>.</span></Link><div className="nav-links"><Link href="/tac-dong-cot-song">Tác động cột sống</Link><Link href="/lich-khai-giang">Lịch khai giảng</Link><Link href="/kien-thuc">Kiến thức</Link></div><Link className="button button-small button-dark" href="/dang-ky-tu-van">Nhận tư vấn</Link></nav></div></header><section className="page-hero"><div className="container"><p className="eyebrow">LỘ TRÌNH ĐÀO TẠO · YOGA</p><h1>{content.title}</h1><p>{content.intro}</p></div></section><section className="section container"><div className="section-heading"><p className="eyebrow">CÁCH TIẾP CẬN</p><h2>Tiến bộ theo mục tiêu cá nhân.</h2></div><div className="branch-grid">{content.principles.map((item, index) => <article className="branch-note" key={item}><span className="package-code">0{index + 1}</span><p>{item}</p></article>)}</div></section><section className="section section-tint"><div className="container"><div className="section-heading"><p className="eyebrow">B1 · B2 · B3</p><h2>Chọn mức học phù hợp với thời gian và mục tiêu.</h2></div><div className="package-grid">{content.packages.map((item) => <Link className="package-card" href={`/khoa-hoc/${item.slug}`} key={item.code}><div className="package-top"><span className="package-code">{item.code}</span><span>{item.requiresScreening ? 'Có xét phù hợp' : 'Chương trình nền tảng'}</span></div><h3>{item.name}</h3><p>{item.summary}</p><div className="package-meta"><span>{item.accessMonths} tháng nội dung</span><span>{item.includesCertification ? 'Có đánh giá theo chương trình' : 'Không bao gồm chứng nhận'}</span></div></Link>)}</div></div></section><section className="section container callout-section"><div><p className="eyebrow">LƯU Ý</p><h2>Không có một kết quả cố định cho mọi người.</h2><p>Mộc Việt tập trung vào cách học, kỹ thuật phù hợp, khả năng duy trì và phản hồi trong phạm vi chương trình.</p></div><Link className="button button-dark" href="/dang-ky-tu-van">Trao đổi mục tiêu</Link></section><footer className="site-footer"><div className="container footer-bottom"><span>© 2026 Mộc Việt</span><span>Nội dung đào tạo không thay thế tư vấn y tế.</span></div></footer></main>
}
